# Generated by Django 4.1 on 2024-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_package', models.CharField(max_length=100)),
                ('service_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
